language: node_js
before_install:
  - cd parking-picker-ui
  - npm install
  - cd ../backend
  - npm install
  - cd ../
node_js:
  - "10"
deploy:
  provider: heroku
  app: parking-picker
  on:
    repo: janbro/CEN3031-Group1
    branch: master
